export const ADD_TASK = 'ADD_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const REMOVE_TASK = 'REMOVE_TASK';
export const SELECT_ALL_TASK = 'SELECT_ALL_TASK';
export const REMOVE_SELECT_TASKS = 'REMOVE_SELECT_TASKS';
export const CHANGE_TASK_TITLE = 'CHANGE_TASK_TITLE';
export const FILTER_TASKS =  'FILTER_TASKS';
